[package]
name = "clipboard-downscaler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "0.7.1"
arboard = "2.1.1"
image = "0.24.3"

[build-dependencies]
windres = "*"